### ISSUE TITLE
Option to remove styles

### ISSUE THREAD

**Issue by alienlebarge** [gfscott/eleventy-plugin-vimeo-embed#14]
Hi ✌️,

It would be great to have an option to:
- remove style in the iframe or add a `class`
- remove style of the container `div`

It will let people use their own CSS to style the embed

So we can get something like that 👍 
```html
<div [class="myClass"]>
  <iframe src="https://player.vimeo.com/video/454091293" frameborder="0" allow="autoplay; fullscreen" allowfullscreen>  </iframe>
</div>
```

Here's a live exemple of the kind of embed I dream of: https://codepen.io/alienlebarge/pen/MWyEVZJ

Great job by the way 😃

**Comment by gfscott** [comment]
That's a great idea, @alienlebarge, thanks for filing an issue! 👍🏻 

There’s already an option to change the wrapper class name to whatever you'd like:

```
eleventyConfig.addPlugin(embedVimeo, {
  embedClass: 'myClass'
});
```

But adding an option to edit or remove the inline styles — that's a good call. I'll add it to the list!
