### ISSUE TITLE
Thumbnail images "The image you are requesting does not exist..."

### ISSUE THREAD

**Issue by Nepherim** [gfscott/eleventy-plugin-vimeo-embed#42]
Vimeo thumbnails of the form img src="https://i.imgur.com/1109226.png" no longer function:
![image](https://user-images.githubusercontent.com/235445/161393754-3fa2af5e-65a4-4fdc-8eed-8987d177cca6.png)

ref: https://developer.vimeo.com/api/upload/thumbnails

**Comment by gfscott** [comment]
👍🏻 Thanks for filing this issue! Will look into patching it ASAP.

**Comment by gfscott** [comment]
@Nepherim Just trying to duplicate what you're seeing and everything's still working for me. It seems like in this case it's just that imgur has removed the image, so you're getting this placeholder instead. But I'm not sure it's an issue with this plugin (which doesn't have an option for custom thumbnail images right now).

Can you share the relevant lines of your markdown file, as well as the HTML output you're seeing? That'll help me diagnose the cause of the issue.

**Comment by Nepherim** [comment]
There was a mis-configuration on my side... everything works just great, nothing to see here :)

Thanks for the quick response, and also the great plugin!

**Comment by gfscott** [comment]
Great, glad it worked out!
